import type { Metadata } from 'next'

export const metadata: Metadata = {
  title: 'Dashboard School Management System',
  description: 'Generated by create next app',
}

export default function DashboardLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return <section>{children}</section>
}
