import type { Metadata } from 'next'
import localFont from 'next/font/local'
import './globals.css'

const farsiAdadFont = localFont({
  src: './fonts/FarsiAdad.woff2',
  variable: '--font-farsi-adad',
  weight: '100 900',
})
const farsiFont = localFont({
  src: './fonts/FarsiFont.woff2',
  variable: '--font-farsi',
  weight: '100 900',
})

export const metadata: Metadata = {
  title: 'School Management System',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang="en">
      <body
        className={`${farsiAdadFont.variable} ${farsiFont.variable} antialiased`}
      >
        {children}
      </body>
    </html>
  )
}
